### ISSUE TITLE
Fix test_setup_sregs unit test on AMD

### ISSUE THREAD

**Issue by serban300** [firecracker-microvm/firecracker#1016]
The test is located in: arch/src/x86_64/regs.rs

This is the output: 
```
Expected :kvm_sregs { cs: kvm_segment { base: 0, limit: 1048575, selector: 8, type_: 11, present: 1, dpl: 0, db: 0, s: 1, l: 1, g: 1, avl: 0, unusable: 0, padding: 0 }, ds: kvm_segment { base: 0, limit: 1048575, selector: 16, type_: 3, present: 1, dpl: 0, db: 1, s: 1, l: 0, g: 1, avl: 0, unusable: 0, padding: 0 }, es: kvm_segment { base: 0, limit: 1048575, selector: 16, type_: 3, present: 1, dpl: 0, db: 1, s: 1, l: 0, g: 1, avl: 0, unusable: 0, padding: 0 }, fs: kvm_segment { base: 0, limit: 1048575, selector: 16, type_: 3, present: 1, dpl: 0, db: 1, s: 1, l: 0, g: 1, avl: 0, unusable: 0, padding: 0 }, gs: kvm_segment { base: 0, limit: 1048575, selector: 16, type_: 3, present: 1, dpl: 0, db: 1, s: 1, l: 0, g: 1, avl: 0, unusable: 0, padding: 0 }, ss: kvm_segment { base: 0, limit: 1048575, selector: 16, type_: 3, present: 1, dpl: 0, db: 1, s: 1, l: 0, g: 1, avl: 0, unusable: 0, padding: 0 }, tr: kvm_segment { base: 0, limit: 1048575, selector: 24, type_: 11, present: 1, dpl: 0, db: 0, s: 0, l: 0, g: 1, avl: 0, unusable: 0, padding: 0 }, ldt: kvm_segment { base: 0, limit: 65535, selector: 0, type_: 2, present: 1, dpl: 0, db: 0, s: 0, l: 0, g: 0, avl: 0, unusable: 0, padding: 0 }, gdt: kvm_dtable { base: 1280, limit: 31, padding: [0, 0, 0] }, idt: kvm_dtable { base: 1312, limit: 7, padding: [0, 0, 0] }, cr0: 3758096401, cr2: 0, cr3: 36864, cr4: 32, cr8: 0, efer: 1280, apic_base: 4276095232, interrupt_bitmap: [0, 0, 0, 0] }
Actual   :kvm_sregs { cs: kvm_segment { base: 0, limit: 1048575, selector: 8, type_: 11, present: 1, dpl: 0, db: 0, s: 1, l: 1, g: 0, avl: 0, unusable: 0, padding: 0 }, ds: kvm_segment { base: 0, limit: 1048575, selector: 16, type_: 3, present: 1, dpl: 0, db: 1, s: 1, l: 0, g: 0, avl: 0, unusable: 0, padding: 0 }, es: kvm_segment { base: 0, limit: 1048575, selector: 16, type_: 3, present: 1, dpl: 0, db: 1, s: 1, l: 0, g: 0, avl: 0, unusable: 0, padding: 0 }, fs: kvm_segment { base: 0, limit: 1048575, selector: 16, type_: 3, present: 1, dpl: 0, db: 1, s: 1, l: 0, g: 0, avl: 0, unusable: 0, padding: 0 }, gs: kvm_segment { base: 0, limit: 1048575, selector: 16, type_: 3, present: 1, dpl: 0, db: 1, s: 1, l: 0, g: 0, avl: 0, unusable: 0, padding: 0 }, ss: kvm_segment { base: 0, limit: 1048575, selector: 16, type_: 3, present: 1, dpl: 0, db: 1, s: 1, l: 0, g: 0, avl: 0, unusable: 0, padding: 0 }, tr: kvm_segment { base: 0, limit: 1048575, selector: 24, type_: 11, present: 1, dpl: 0, db: 0, s: 0, l: 0, g: 0, avl: 0, unusable: 0, padding: 0 }, ldt: kvm_segment { base: 0, limit: 65535, selector: 0, type_: 2, present: 1, dpl: 0, db: 0, s: 0, l: 0, g: 0, avl: 0, unusable: 0, padding: 0 }, gdt: kvm_dtable { base: 1280, limit: 31, padding: [0, 0, 0] }, idt: kvm_dtable { base: 1312, limit: 7, padding: [0, 0, 0] }, cr0: 3758096401, cr2: 0, cr3: 36864, cr4: 32, cr8: 0, efer: 1280, apic_base: 4276095232, interrupt_bitmap: [0, 0, 0, 0] }

thread 'x86_64::regs::tests::test_setup_sregs' panicked at 'assertion failed: `(left == right)`
  left: `kvm_sregs { cs: kvm_segment { base: 0, limit: 1048575, selector: 8, type_: 11, present: 1, dpl: 0, db: 0, s: 1, l: 1, g: 1, avl: 0, unusable: 0, padding: 0 }, ds: kvm_segment { base: 0, limit: 1048575, selector: 16, type_: 3, present: 1, dpl: 0, db: 1, s: 1, l: 0, g: 1, avl: 0, unusable: 0, padding: 0 }, es: kvm_segment { base: 0, limit: 1048575, selector: 16, type_: 3, present: 1, dpl: 0, db: 1, s: 1, l: 0, g: 1, avl: 0, unusable: 0, padding: 0 }, fs: kvm_segment { base: 0, limit: 1048575, selector: 16, type_: 3, present: 1, dpl: 0, db: 1, s: 1, l: 0, g: 1, avl: 0, unusable: 0, padding: 0 }, gs: kvm_segment { base: 0, limit: 1048575, selector: 16, type_: 3, present: 1, dpl: 0, db: 1, s: 1, l: 0, g: 1, avl: 0, unusable: 0, padding: 0 }, ss: kvm_segment { base: 0, limit: 1048575, selector: 16, type_: 3, present: 1, dpl: 0, db: 1, s: 1, l: 0, g: 1, avl: 0, unusable: 0, padding: 0 }, tr: kvm_segment { base: 0, limit: 1048575, selector: 24, type_: 11, present: 1, dpl: 0, db: 0, s: 0, l: 0, g: 1, avl: 0, unusable: 0, padding: 0 }, ldt: kvm_segment { base: 0, limit: 65535, selector: 0, type_: 2, present: 1, dpl: 0, db: 0, s: 0, l: 0, g: 0, avl: 0, unusable: 0, padding: 0 }, gdt: kvm_dtable { base: 1280, limit: 31, padding: [0, 0, 0] }, idt: kvm_dtable { base: 1312, limit: 7, padding: [0, 0, 0] }, cr0: 3758096401, cr2: 0, cr3: 36864, cr4: 32, cr8: 0, efer: 1280, apic_base: 4276095232, interrupt_bitmap: [0, 0, 0, 0] }`,
 right: `kvm_sregs { cs: kvm_segment { base: 0, limit: 1048575, selector: 8, type_: 11, present: 1, dpl: 0, db: 0, s: 1, l: 1, g: 0, avl: 0, unusable: 0, padding: 0 }, ds: kvm_segment { base: 0, limit: 1048575, selector: 16, type_: 3, present: 1, dpl: 0, db: 1, s: 1, l: 0, g: 0, avl: 0, unusable: 0, padding: 0 }, es: kvm_segment { base: 0, limit: 1048575, selector: 16, type_: 3, present: 1, dpl: 0, db: 1, s: 1, l: 0, g: 0, avl: 0, unusable: 0, padding: 0 }, fs: kvm_segment { base: 0, limit: 1048575, selector: 16, type_: 3, present: 1, dpl: 0, db: 1, s: 1, l: 0, g: 0, avl: 0, unusable: 0, padding: 0 }, gs: kvm_segment { base: 0, limit: 1048575, selector: 16, type_: 3, present: 1, dpl: 0, db: 1, s: 1, l: 0, g: 0, avl: 0, unusable: 0, padding: 0 }, ss: kvm_segment { base: 0, limit: 1048575, selector: 16, type_: 3, present: 1, dpl: 0, db: 1, s: 1, l: 0, g: 0, avl: 0, unusable: 0, padding: 0 }, tr: kvm_segment { base: 0, limit: 1048575, selector: 24, type_: 11, present: 1, dpl: 0, db: 0, s: 0, l: 0, g: 0, avl: 0, unusable: 0, padding: 0 }, ldt: kvm_segment { base: 0, limit: 65535, selector: 0, type_: 2, present: 1, dpl: 0, db: 0, s: 0, l: 0, g: 0, avl: 0, unusable: 0, padding: 0 }, gdt: kvm_dtable { base: 1280, limit: 31, padding: [0, 0, 0] }, idt: kvm_dtable { base: 1312, limit: 7, padding: [0, 0, 0] }, cr0: 3758096401, cr2: 0, cr3: 36864, cr4: 32, cr8: 0, efer: 1280, apic_base: 4276095232, interrupt_bitmap: [0, 0, 0, 0] }`', arch/src/x86_64/regs.rs:444:9
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:221
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:476
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:390
   6: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:345
   7: arch::x86_64::regs::tests::test_setup_sregs
             at arch/src/x86_64/regs.rs:444
   8: arch::x86_64::regs::tests::test_setup_sregs::{{closure}}
             at arch/src/x86_64/regs.rs:432
   9: core::ops::function::FnOnce::call_once
             at libcore/ops/function.rs:238
  10: <F as alloc::boxed::FnBox<A>>::call_box
             at libtest/lib.rs:1468
             at libcore/ops/function.rs:238
             at liballoc/boxed.rs:672
  11: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
```

The issue is that for each kvm_segment , the expected value for the parametr `g` is 1 while the actual value is 0

**Comment by serban300** [comment]
This seems to be the desired behavior when calling `KVM_GET_SREGS` for svm. [Here](https://github.com/torvalds/linux/blob/9e98c678c2d6ae3a17cb2de55d17f69dddaa231b/arch/x86/kvm/svm.c#L2396-L2404) is the code.

**Comment by andreeaflorescu** [comment]
The test looks a bit bogus to me. Here is why:
- in the function `setup_sregs` we are running 2 functions: `configure_segments_and_sregs` and `setup_page_tables` that alter the sregs.
- to test this function we are running the same 2 functions in the test.

To me it looks more like a duplication of the code (same code in function, same code in the test) and not a test in itself. When working on fixing the issues with AMD, can you also update this test?

**Comment by serban300** [comment]
> The test looks a bit bogus to me. Here is why:
> 
>     * in the function `setup_sregs` we are running 2 functions: `configure_segments_and_sregs` and `setup_page_tables` that alter the sregs.
> 
>     * to test this function we are running the same 2 functions in the test.
> 
> 
> To me it looks more like a duplication of the code (same code in function, same code in the test) and not a test in itself. When working on fixing the issues with AMD, can you also update this test?

It's a good point, I agree. I will update this test.
