### ISSUE TITLE
Fix test_error_tap_set_ip on AMD

### ISSUE THREAD

**Issue by serban300** [firecracker-microvm/firecracker#1018]
Output:

```
thread 'virtio::net::tests::test_error_tap_set_ip' panicked at 'assertion failed: false', devices/src/virtio/net.rs:1320:18
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:221
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:476
   5: std::panicking::begin_panic
             at libstd/panicking.rs:410
   6: devices::virtio::net::tests::test_error_tap_set_ip
             at devices/src/virtio/net.rs:1320
   7: devices::virtio::net::tests::test_error_tap_set_ip::{{closure}}
             at devices/src/virtio/net.rs:1305
   8: core::ops::function::FnOnce::call_once
             at libcore/ops/function.rs:238
   9: <F as alloc::boxed::FnBox<A>>::call_box
             at libtest/lib.rs:1468
             at libcore/ops/function.rs:238
             at liballoc/boxed.rs:672
  10: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102


```

**Comment by serban300** [comment]
I can't reproduce this issue anymore. Probably it was caused by a config that I used. Closing for the moment.
