### ISSUE TITLE
Panic messages in seccomp tests ouput

### ISSUE THREAD

**Issue by alexandruag** [firecracker-microvm/firecracker#1247]
Unit tests from the `seccomp` crate will pass when running `cargo test`, but the output also contains a lot of panic messages. This appears to happen starting with 35b73437641. Example output:

```
running 15 tests
test tests::test_bpf_expanding_functions ... ok
test tests::test_bpf_functions ... ok
test tests::test_error_messages ... ok
test tests::test_filter_bpf_output_dword ... ok
test tests::test_from_seccomp_action ... ok
test tests::test_filter_bpf_output_qword ... ok
test tests::test_rule_bpf_output ... ok
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:345:21
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:345:21
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:345:21
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:345:21
test tests::test_rule_many_conditions_bpf_output ... ok
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:345:21
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:345:thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:345:21
21
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:345:21
test tests::test_eq_operator ... ok
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:345:21
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:345:21
test tests::test_ge_operator ... ok
test tests::test_lt_operator ... ok
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:345:21
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:345:21
test tests::test_le_operator ... ok
test tests::test_masked_eq_operator ... ok
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:345:21
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:345:21
test tests::test_gt_operator ... ok
test tests::test_ne_operator ... ok

test result: ok. 15 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
```

**Comment by serban300** [comment]
This happens because the thread gets killed when a seccomp denial occurs. I don't know if the message can be avoided.

**Comment by serban300** [comment]
The panics are caused by [this](https://doc.rust-lang.org/src/std/thread/mod.rs.html#1329) line of code.
