### ISSUE TITLE
Build with libc results in error (bad syscall) upon instance start

### ISSUE THREAD

**Issue by ustiugov** [firecracker-microvm/firecracker#1960]
I tried to build Firecracker with libc, instead of musl, and observed that Firecracker raises the following error with the latest firecracker code (57f4c7ca14a31c5536f188cacb669d2cad32b9ca).

```
ERROR:src/vmm/src/signal_handler.rs:37] Shutting down VM after intercepting a bad syscall (39).
```
Guest:
* hello-linux.bin kernel
* rootfs build according to docs (Alpine), build from the following docker image `ustiugov/helloworld:runner_workload`

Host:
* Ubuntu 18.04: 4.15.0-76-generic

A complete log:
```
Running Firecracker v0.21.0
2020-06-16T13:31:24.898331416 [anonymous-instance:INFO:src/api_server/src/parsed_request.rs:124] The API server received a Put request on "/boot-source" with body "{n "kernel_image_path": "/home/ustiugov/rootfs_all/hello-vmlinux.bin",n "boot_args": "console=ttyS0 reboot=k panic=1 pci=off"n }".
2020-06-16T13:31:24.898602853 [anonymous-instance:INFO:src/api_server/src/parsed_request.rs:89] The request was executed successfully. Status code: 204 No Content.
2020-06-16T13:31:24.910903560 [anonymous-instance:INFO:src/api_server/src/parsed_request.rs:124] The API server received a Put request on "/drives/rootfs" with body "{n "drive_id": "rootfs",n "path_on_host": "/home/ustiugov/rootfs_all/rootfs.ext4",n "is_root_device": true,n "is_read_only": falsen }".
2020-06-16T13:31:24.911165063 [anonymous-instance:INFO:src/api_server/src/parsed_request.rs:89] The request was executed successfully. Status code: 204 No Content.
2020-06-16T13:31:24.921777311 [anonymous-instance:INFO:src/api_server/src/parsed_request.rs:124] The API server received a Put request on "/network-interfaces/eth0" with body "{n "iface_id": "eth0",n "guest_mac": "AA:FC:00:00:00:01",n "host_dev_name": "tap0"n }".
2020-06-16T13:31:24.923636799 [anonymous-instance:INFO:src/api_server/src/parsed_request.rs:89] The request was executed successfully. Status code: 204 No Content.
2020-06-16T13:31:24.934104250 [anonymous-instance:INFO:src/api_server/src/parsed_request.rs:124] The API server received a Put request on "/machine-config" with body "{n "vcpu_count": 1,n "mem_size_mib": 512,n "ht_enabled": falsen }".
2020-06-16T13:31:24.934236010 [anonymous-instance:INFO:src/api_server/src/parsed_request.rs:89] The request was executed successfully. Status code: 204 No Content.
2020-06-16T13:31:24.944399963 [anonymous-instance:INFO:src/api_server/src/parsed_request.rs:124] The API server received a Put request on "/metrics" with body "{n "metrics_path": "/tmp/metrics.fifo"n }".
2020-06-16T13:31:24.944527673 [anonymous-instance:INFO:src/api_server/src/parsed_request.rs:89] The request was executed successfully. Status code: 204 No Content.
2020-06-16T13:31:24.954896116 [anonymous-instance:INFO:src/api_server/src/parsed_request.rs:124] The API server received a Put request on "/actions" with body "{n "action_type": "InstanceStart"n }".
2020-06-16T13:31:24.969572427 [anonymous-instance:ERROR:src/vmm/src/signal_handler.rs:37] Shutting down VM after intercepting a bad syscall (39).

```

**Comment by aghecenco** [comment]
`SYS_getpid` is getting issued, and it's not whitelisted so it causes a seccomp fault that terminates firecracker. To work around the issue, you can start with seccomp disabled (`--seccomp-level 0` in the command line) but it would be interesting to know where the syscall is coming from. Can you run firecracker under `strace` to find it?
We also have a bunch of seccomp improvements in mind, one of them being an externally specified whitelist so users don't have to recompile firecracker to allow new syscalls: #1366

**Comment by ustiugov** [comment]
@aghecenco Thank you, the workaround seems to be a plausible option for now (I intend to go back to musl later).

The tail of the strace log
```
ioctl(26, KVM_CREATE_VCPU, 0)           = 28
mmap(NULL, 12288, PROT_READ|PROT_WRITE, MAP_SHARED, 28, 0) = 0x7fde2fc11000
eventfd2(0, EFD_NONBLOCK)               = 29
epoll_ctl(6, EPOLL_CTL_ADD, 0, {EPOLLIN, {u32=0, u64=0}}) = 0
dup(25)                                 = 30
dup(29)                                 = 31
eventfd2(0, EFD_NONBLOCK)               = 32
eventfd2(0, EFD_NONBLOCK)               = 33
dup(33)                                 = 34
dup(32)                                 = 35
dup(31)                                 = 36
dup(32)                                 = 37
ioctl(26, KVM_IRQFD, 0x7fff66bbd700)    = 0
ioctl(26, KVM_IRQFD, 0x7fff66bbd700)    = 0
ioctl(26, KVM_IRQFD, 0x7fff66bbd700)    = 0
epoll_ctl(6, EPOLL_CTL_ADD, 16, {EPOLLIN, {u32=16, u64=16}}) = 0
ioctl(26, KVM_IOEVENTFD, 0x7fff66bbe558) = 0
ioctl(26, KVM_IRQFD, 0x7fff66bbe5d0)    = 0
epoll_ctl(6, EPOLL_CTL_ADD, 23, {EPOLLIN, {u32=23, u64=23}}) = 0
ioctl(26, KVM_IOEVENTFD, 0x7fff66bbe718) = 0
ioctl(26, KVM_IOEVENTFD, 0x7fff66bbe718) = 0
ioctl(26, KVM_IRQFD, 0x7fff66bbe790)    = 0
ioctl(28, KVM_SET_CPUID2, 0x55dcb4d747d0) = 0
ioctl(28, KVM_SET_MSRS, 0x55dcb4d74d10) = 10
ioctl(28, KVM_SET_REGS, {rax=0, ..., rsp=0x8ff0, rbp=0x8ff0, ..., rip=0x1000000, rflags=0x2}) = 0
ioctl(28, KVM_SET_FPU, 0x7fff66bbdec0)  = 0
ioctl(28, KVM_GET_SREGS, {cs={base=0xffff0000, limit=65535, selector=61440, type=11, present=1, dpl=0, db=0, s=1, l=0, g=0, avl=0}, ...}) = 0
ioctl(28, KVM_SET_SREGS, {cs={base=0, limit=1048575, selector=8, type=11, present=1, dpl=0, db=0, s=1, l=1, g=1, avl=0}, ...}) = 0
ioctl(28, KVM_GET_LAPIC, 0x7fff66bbc578) = 0
ioctl(28, KVM_SET_LAPIC, 0x7fff66bbcdd8) = 0
ioctl(0, TCGETS, {B38400 opost isig icanon echo ...}) = 0
ioctl(0, TCGETS, {B38400 opost isig icanon echo ...}) = 0
ioctl(0, TCGETS, {B38400 opost isig icanon echo ...}) = 0
ioctl(0, SNDCTL_TMR_START or TCSETS, {B38400 opost -isig -icanon -echo ...}) = 0
ioctl(0, TCGETS, {B38400 opost -isig -icanon -echo ...}) = 0
rt_sigaction(SIGRT_2, {sa_handler=0x55dcb32ae390, sa_mask=~[RTMIN RT_1], sa_flags=SA_RESTORER|SA_SIGINFO, sa_restorer=0x7fde2f404890}, NULL, 8) = 0
mmap(NULL, 2101248, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_STACK, -1, 0) = 0x7fde2e9e7000
mprotect(0x7fde2e9e8000, 2097152, PROT_READ|PROT_WRITE) = 0
clone(child_stack=0x7fde2ebe6eb0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7fde2ebe79d0, tls=0x7fde2ebe7700, child_tidptr=0x7fde2ebe79d0) = 1625301
prctl(PR_SET_NO_NEW_PRIVS, 1, 0, 0, 0)  = 0
prctl(PR_SET_SECCOMP, SECCOMP_MODE_FILTER, {len=459, filter=0x55dcb4d76a60}) = 0
futex(0x7fde280025a8, FUTEX_WAKE_PRIVATE, 1) = 1
getpid()                                = 39
--- SIGSYS {si_signo=SIGSYS, si_code=SYS_SECCOMP, si_call_addr=0x7fde2eece8e7, si_syscall=__NR_getpid, si_arch=AUDIT_ARCH_X86_64} ---
write(3, "2020-06-16T15:02:23.827850251 [a"..., 146) = 146
write(24, "{\"utc_timestamp_ms\":3648140888,\""..., 2596) = 2596
exit_group(148)                         = ?
+++ exited with 148 +++

```

**Comment by alindima** [comment]
I have started to investigate on this issue.

After reproducing it, I managed to get the stack trace that lead to the error:

    #0  0x00007ffff72ac300 in getpid () from /lib64/libc.so.6
    #1  0x00007ffff77bd744 in pthread_kill () from /lib64/libpthread.so.0
    #2  0x00005555557940bb in vmm_sys_util::unix::signal::Killable::kill (self=0x555555c87940, num=34) at /home/ec2-user/.cargo/registry/src/github.com-1ecc6299db9ec823/vmm-sys-util-0.4.0/src/unix/signal.rs:430
    #3  0x000055555577e863 in vmm::vstate::VcpuHandle::send_event (self=0x555555c87920, event=...) at src/vmm/src/vstate.rs:1394
    #4  0x00005555556b0f24 in vmm::Vmm::resume_vcpus (self=0x7fffffff9940) at src/vmm/src/lib.rs:301
    #5  0x0000555555625073 in vmm::builder::build_microvm_for_boot (vm_resources=0x7fffffffb7c0, event_manager=0x7fffffffbf30, seccomp_filter=...) at src/vmm/src/builder.rs:351
    #6  0x000055555573a50d in vmm::rpc_interface::PrebootApiController::handle_preboot_request (self=0x7fffffffb868, request=...) at src/vmm/src/rpc_interface.rs:300
    #7  0x00005555555dcd4a in vmm::rpc_interface::PrebootApiController::build_microvm_from_requests (seccomp_filter=..., event_manager=0x7fffffffbf30, instance_info=..., recv_req=..., respond=...)
        at /home/ec2-user/code/firecracker/src/vmm/src/rpc_interface.rs:237
    #8  0x00005555555ec68d in firecracker::api_server_adapter::run_with_api (seccomp_filter=..., config_json=..., bind_path=..., instance_info=..., start_time_us=..., start_time_cpu_us=...) at src/firecracker/src/api_server_adapter.rs:166
    #9  0x00005555555e80c7 in firecracker::main () at src/firecracker/src/main.rs:245

Apparently, the `pthread_kill` function from the glibc implementation is calling the `getpid()` syscall, which violates current seccomp rules.

After searching through the source code of glibc, this is indeed the case, as you can see [here](https://gitlab.com/LinkiTools/glibc/-/blob/glibc-2.26/sysdeps/unix/sysv/linux/pthread_kill.c#L53).

The standard musl `pthread_kill` implementation, which can be found [here](https://git.musl-libc.org/cgit/musl/tree/src/thread/pthread_kill.c), is not calling `getpid`, therefore is not violating any seccomp rules, and that's why this is only reproducible when building with dynamic glibc. 

This difference is rooted in the syscall each implementation chooses to use in order to kill the thread (`tkill` vs `tgkill`).
`tgkill` requires the thread group id, which is retrieved via the `getpid` syscall.

I will look into this to find a fix.

**Comment by alindima** [comment]
This issue is now fixed by this [commit](https://github.com/firecracker-microvm/firecracker/commit/fa24d94175bf9411b26878f67c536792b4deeb5c)
