### ISSUE TITLE
[Feature Request] Automatically run python doctests

### ISSUE THREAD

**Issue by JonathanWoollett-Light** [firecracker-microvm/firecracker#3035]
# Feature Request

A small number of [pytest doctests](https://docs.python.org/3/library/doctest.html) are present in the project, largely for documentation.

It would be beneficial to automatically run these to verify they are correct.

## Describe the desired solution

`./tool/devtool test` automatically runs all pytest doctests.

## Checks

- [x] Have you searched the Firecracker Issues database for similar requests?
- [x] Have you read all the existing relevant Firecracker documentation?
- [x] Have you read and understood Firecracker's core tenets?

**Comment by sarimaleem** [comment]
@JBYoshi and I would like to work on this. We're doing a class project for UT Austin's virtualization class, where we're supposed to work on issues in virtualization-related open source projects. Is this issue open for us to work on?

**Comment by JonathanWoollett-Light** [comment]
@sarimaleem Contribution would be really appreciated here, you should always feel free to contribute on open issues, you don't need to ask.

**Comment by Ecazares15** [comment]
Hello!

We are students from the University of Texas at Austin taking a virtualization course (cs360v) looking for opportunities to contribute to an open source project for class credit.

Could I be assigned to this?

**Comment by roypat** [comment]
So, running the doctests is just a matter of doing `pytest --doctest-modules framework/` inside of `tests`. However, currently they all fail

<details>

```
root@d20dca6270c9:/firecracker/tests# pytest --doctest-modules framework/
================================== test session starts ===================================
platform linux -- Python 3.12.3, pytest-8.3.3, pluggy-1.5.0 -- /opt/venv/bin/python
cachedir: ../build/pytest_cache
metadata: {'Python': '3.12.3', 'Platform': 'Linux-6.8.0-47-generic-x86_64-with-glibc2.39', 'Packages': {'pytest': '8.3.3', 'pluggy': '1.5.0'}, 'Plugins': {'json-report': '1.5.0', 'metadata': '3.1.1', 'timeout': '2.3.1', 'rerunfailures': '14.0', 'xdist': '3.6.1'}}
rootdir: /firecracker/tests
configfile: pytest.ini
plugins: json-report-1.5.0, metadata-3.1.1, timeout-2.3.1, rerunfailures-14.0, xdist-3.6.1
timeout: 300.0s
timeout method: signal
timeout func_only: False
collected 7 items                                                                        

framework/gitlint_rules.py::framework.gitlint_rules.EndsSigned.validate FAILED     [ 14%]
framework/properties.py::framework.properties.get_host_os FAILED                   [ 28%]
framework/properties.py::framework.properties.get_os_version FAILED                [ 42%]
framework/utils.py::framework.utils.Timeout FAILED                                 [ 57%]
framework/utils_imdsv2.py::framework.utils_imdsv2.IMDSv2Client FAILED              [ 71%]
framework/utils_imdsv2.py::framework.utils_imdsv2.IMDSv2Client.get FAILED          [ 85%]
framework/utils_imdsv2.py::framework.utils_imdsv2.imdsv2_get FAILED                [100%]

======================================== FAILURES ========================================
_________________ [doctest] framework.gitlint_rules.EndsSigned.validate __________________
023 Validates Signed-off-by and Co-authored-by tags as Linux's scripts/checkpatch.pl
024 
025         >>> from gitlint.tests.base import BaseTestCase
UNEXPECTED EXCEPTION: ModuleNotFoundError("No module named 'gitlint.tests'")
Traceback (most recent call last):
  File "/usr/lib/python3.12/doctest.py", line 1361, in __run
    exec(compile(example.source, filename, "single",
  File "<doctest framework.gitlint_rules.EndsSigned.validate[0]>", line 1, in <module>
ModuleNotFoundError: No module named 'gitlint.tests'
/firecracker/tests/framework/gitlint_rules.py:25: UnexpectedException
_______________________ [doctest] framework.properties.get_host_os _______________________
039 
040     Extract OS information from the kernel if it's there.
041 
042     This only works for AL2 and AL2023
043 
044     >>> get_host_os("6.1.41-63.118.amzn2023.x86_64")
Expected:
    amzn2023
Got:
    'amzn2023'

/firecracker/tests/framework/properties.py:44: DocTestFailure
_____________________ [doctest] framework.properties.get_os_version ______________________
027 Get the OS version
028 
029     >>> get_os_version()
Expected:
    Ubuntu 18.04.6 LTS
Got:
    'Ubuntu 24.04.1 LTS'

/firecracker/tests/framework/properties.py:29: DocTestFailure
___________________________ [doctest] framework.utils.Timeout ____________________________
655 
656     A Context Manager to timeout sections of code.
657 
658     >>> with Timeout(30):
UNEXPECTED EXCEPTION: IndentationError("expected an indented block after 'with' statement on line 1", ('<doctest framework.utils.Timeout[0]>', 1, 18, 'with Timeout(30):\n', 1, -1))
Traceback (most recent call last):
  File "/usr/lib/python3.12/doctest.py", line 1361, in __run
    exec(compile(example.source, filename, "single",
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<doctest framework.utils.Timeout[0]>", line 1
    with Timeout(30):
                     ^
IndentationError: expected an indented block after 'with' statement on line 1
/firecracker/tests/framework/utils.py:658: UnexpectedException
_____________________ [doctest] framework.utils_imdsv2.IMDSv2Client ______________________
024 
025     A simple IMDSv2 client.
026 
027     >>> IMDSv2Client().get("/meta-data/instance-type")
UNEXPECTED EXCEPTION: ConnectTimeout(MaxRetryError("HTTPConnectionPool(host='169.254.169.254', port=80): Max retries exceeded with url: /latest/api/token (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eca3a7701d0>, 'Connection to 169.254.169.254 timed out. (connect timeout=2)'))"))
Traceback (most recent call last):
  File "/opt/venv/lib/python3.12/site-packages/urllib3/connection.py", line 199, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/opt/venv/lib/python3.12/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
TimeoutError: timed out
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/opt/venv/lib/python3.12/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/urllib3/connectionpool.py", line 495, in _make_request
    conn.request(
  File "/opt/venv/lib/python3.12/site-packages/urllib3/connection.py", line 441, in request
    self.endheaders()
  File "/usr/lib/python3.12/http/client.py", line 1331, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.12/http/client.py", line 1091, in _send_output
    self.send(msg)
  File "/usr/lib/python3.12/http/client.py", line 1035, in send
    self.connect()
  File "/opt/venv/lib/python3.12/site-packages/urllib3/connection.py", line 279, in connect
    self.sock = self._new_conn()
                ^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/urllib3/connection.py", line 208, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPConnection object at 0x7eca3a7701d0>, 'Connection to 169.254.169.254 timed out. (connect timeout=2)')
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/opt/venv/lib/python3.12/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/urllib3/connectionpool.py", line 843, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='169.254.169.254', port=80): Max retries exceeded with url: /latest/api/token (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eca3a7701d0>, 'Connection to 169.254.169.254 timed out. (connect timeout=2)'))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.12/doctest.py", line 1361, in __run
    exec(compile(example.source, filename, "single",
  File "<doctest framework.utils_imdsv2.IMDSv2Client[0]>", line 1, in <module>
  File "/firecracker/tests/framework/utils_imdsv2.py", line 55, in get
    headers = {IMDSV2_HDR_TOKEN: self.get_token()}
                                 ^^^^^^^^^^^^^^^^
  File "/firecracker/tests/framework/utils_imdsv2.py", line 43, in get_token
    res = requests.put(url, headers=headers, timeout=2)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/requests/api.py", line 130, in put
    return request("put", url, data=data, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/requests/adapters.py", line 688, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='169.254.169.254', port=80): Max retries exceeded with url: /latest/api/token (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eca3a7701d0>, 'Connection to 169.254.169.254 timed out. (connect timeout=2)'))
/firecracker/tests/framework/utils_imdsv2.py:27: UnexpectedException
___________________ [doctest] framework.utils_imdsv2.IMDSv2Client.get ____________________
049 
050         Get a metadata path from IMDSv2
051 
052         >>> IMDSv2Client().get("/meta-data/instance-type")
UNEXPECTED EXCEPTION: ConnectTimeout(MaxRetryError("HTTPConnectionPool(host='169.254.169.254', port=80): Max retries exceeded with url: /latest/api/token (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eca3a776c90>, 'Connection to 169.254.169.254 timed out. (connect timeout=2)'))"))
Traceback (most recent call last):
  File "/opt/venv/lib/python3.12/site-packages/urllib3/connection.py", line 199, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/opt/venv/lib/python3.12/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
TimeoutError: timed out
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/opt/venv/lib/python3.12/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/urllib3/connectionpool.py", line 495, in _make_request
    conn.request(
  File "/opt/venv/lib/python3.12/site-packages/urllib3/connection.py", line 441, in request
    self.endheaders()
  File "/usr/lib/python3.12/http/client.py", line 1331, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.12/http/client.py", line 1091, in _send_output
    self.send(msg)
  File "/usr/lib/python3.12/http/client.py", line 1035, in send
    self.connect()
  File "/opt/venv/lib/python3.12/site-packages/urllib3/connection.py", line 279, in connect
    self.sock = self._new_conn()
                ^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/urllib3/connection.py", line 208, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPConnection object at 0x7eca3a776c90>, 'Connection to 169.254.169.254 timed out. (connect timeout=2)')
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/opt/venv/lib/python3.12/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/urllib3/connectionpool.py", line 843, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='169.254.169.254', port=80): Max retries exceeded with url: /latest/api/token (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eca3a776c90>, 'Connection to 169.254.169.254 timed out. (connect timeout=2)'))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.12/doctest.py", line 1361, in __run
    exec(compile(example.source, filename, "single",
  File "<doctest framework.utils_imdsv2.IMDSv2Client.get[0]>", line 1, in <module>
  File "/firecracker/tests/framework/utils_imdsv2.py", line 55, in get
    headers = {IMDSV2_HDR_TOKEN: self.get_token()}
                                 ^^^^^^^^^^^^^^^^
  File "/firecracker/tests/framework/utils_imdsv2.py", line 43, in get_token
    res = requests.put(url, headers=headers, timeout=2)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/requests/api.py", line 130, in put
    return request("put", url, data=data, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/requests/adapters.py", line 688, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='169.254.169.254', port=80): Max retries exceeded with url: /latest/api/token (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eca3a776c90>, 'Connection to 169.254.169.254 timed out. (connect timeout=2)'))
/firecracker/tests/framework/utils_imdsv2.py:52: UnexpectedException
______________________ [doctest] framework.utils_imdsv2.imdsv2_get _______________________
049 
050         Get a metadata path from IMDSv2
051 
052         >>> IMDSv2Client().get("/meta-data/instance-type")
UNEXPECTED EXCEPTION: ConnectTimeout(MaxRetryError("HTTPConnectionPool(host='169.254.169.254', port=80): Max retries exceeded with url: /latest/api/token (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eca3a7758e0>, 'Connection to 169.254.169.254 timed out. (connect timeout=2)'))"))
Traceback (most recent call last):
  File "/opt/venv/lib/python3.12/site-packages/urllib3/connection.py", line 199, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/opt/venv/lib/python3.12/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
TimeoutError: timed out
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/opt/venv/lib/python3.12/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/urllib3/connectionpool.py", line 495, in _make_request
    conn.request(
  File "/opt/venv/lib/python3.12/site-packages/urllib3/connection.py", line 441, in request
    self.endheaders()
  File "/usr/lib/python3.12/http/client.py", line 1331, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.12/http/client.py", line 1091, in _send_output
    self.send(msg)
  File "/usr/lib/python3.12/http/client.py", line 1035, in send
    self.connect()
  File "/opt/venv/lib/python3.12/site-packages/urllib3/connection.py", line 279, in connect
    self.sock = self._new_conn()
                ^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/urllib3/connection.py", line 208, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPConnection object at 0x7eca3a7758e0>, 'Connection to 169.254.169.254 timed out. (connect timeout=2)')
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/opt/venv/lib/python3.12/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/urllib3/connectionpool.py", line 843, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='169.254.169.254', port=80): Max retries exceeded with url: /latest/api/token (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eca3a7758e0>, 'Connection to 169.254.169.254 timed out. (connect timeout=2)'))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.12/doctest.py", line 1361, in __run
    exec(compile(example.source, filename, "single",
  File "<doctest framework.utils_imdsv2.imdsv2_get[0]>", line 1, in <module>
  File "/firecracker/tests/framework/utils_imdsv2.py", line 55, in get
    headers = {IMDSV2_HDR_TOKEN: self.get_token()}
                                 ^^^^^^^^^^^^^^^^
  File "/firecracker/tests/framework/utils_imdsv2.py", line 43, in get_token
    res = requests.put(url, headers=headers, timeout=2)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/requests/api.py", line 130, in put
    return request("put", url, data=data, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/requests/adapters.py", line 688, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='169.254.169.254', port=80): Max retries exceeded with url: /latest/api/token (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7eca3a7758e0>, 'Connection to 169.254.169.254 timed out. (connect timeout=2)'))
/firecracker/tests/framework/utils_imdsv2.py:52: UnexpectedException

```

</details>

Some are easy to fix (the get_host_os one), some probably just mean looking at gitlint's documentation to check what the correct import is, and the rest is probably a matter of figuring out how to exclude specific doctests from being ran. So for this issue, what would need to be done is

1. Do whatever changes are needed to make `cd tests; pytest --doctest-modules framework/` pass
2. Add the above command to `cmd_test` inside `tools/devtool` somewhere.
