### ISSUE TITLE
CI: Integration Tests Sporadically Fail with 'Cannot add write metrics TimerFd to epoll'

### ISSUE THREAD

**Issue by raduweiss** [firecracker-microvm/firecracker#706]
Integration tests sporadically fail with:

```
---- tests::test_rescan stdout ----
thread 'tests::test_rescan' panicked at 'Cannot add write metrics TimerFd to epoll.: EpollFd(Os { code: 9, kind: Other, message: "Bad file descriptor" })', libcore/result.rs:1009:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
1: std::sys_common::backtrace::print
at libstd/sys_common/backtrace.rs:71
at libstd/sys_common/backtrace.rs:59
2: std::panicking::default_hook::{{closure}}
at libstd/panicking.rs:211
3: std::panicking::default_hook
at libstd/panicking.rs:221
4: std::panicking::rust_panic_with_hook
at libstd/panicking.rs:477
5: std::panicking::continue_panic_fmt
at libstd/panicking.rs:391
6: rust_begin_unwind
at libstd/panicking.rs:326
7: core::panicking::panic_fmt
at libcore/panicking.rs:77
8: core::result::unwrap_failed
at libcore/macros.rs:26
9: <core::result::Result<T, E>>::expect
at libcore/result.rs:835
10: vmm::Vmm::new
at vmm/src/lib.rs:562
11: vmm::tests::create_vmm_object
at vmm/src/lib.rs:1850
12: vmm::tests::test_rescan
at vmm/src/lib.rs:2484
13: vmm::tests::test_rescan::{{closure}}
at vmm/src/lib.rs:2483
14: core::ops::function::FnOnce::call_once
at libcore/ops/function.rs:238
15: <F as alloc::boxed::FnBox<A>>::call_box
at libtest/lib.rs:1461
at libcore/ops/function.rs:238
at liballoc/boxed.rs:646
16: __rust_maybe_catch_panic
at libpanic_unwind/lib.rs:103
```

**Comment by raduweiss** [comment]
Should be addressed by #709.
